config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  get "discography", to: "homes#discography"
  get "members", to: "homes#members"
  get "biography", to: "homes#biography"
  get "sns", to: "homes#sns"
  get "shop", to: "marts#index"
  get "special", to: "homes#special"
  
  get "signup", to: "users#new"
  get "goodbye", to: "users#delete"
  resources :users, only: [:new, :create, :delete]
  
  resources :products
  
  resources :carts, only: [:index] do
    member do
      get :cart
      get :nanika
      get :favorites
    end
    collection do
      get :info
    end
  end
  
  post "add_item", to: "carts#add_item"
  post "update_item", to: "carts#update_item"
  delete "delete_item", to: "carts#delete_item"
  
  resources :microposts, only: [:create, :destroy]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]

  def show
    @cart_items = current_cart.cart_items
  end
  
  def add_item
    if @cart_item.blank?
      @cart_item = current_cart.cart_items.build(product_id: params[:product_id])
    end
    
    @cart_item.quantity += params[:quantity].to_i
    @cart_item.save
    redirect_to ""
  end
  
  def update_item
    @cart_item.update(quantity: params[:quantity].to_i)
    redirect_to ""
  end
  
  def delete_item
    @cart_item.destroy
    redirect_to ""
  end
  
  private
  
  def setup_cart_item!
    @cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def discography
  end

  def members
  end

  def event
  end

  def sns
    @micropost = current_user.microposts.build
    @microposts = current_user.microposts.order(id: :desc)
  end

  def biography
  end

  def special
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_back(fallback_location: root_path)
    else
      @microposts = current_user.microposts.order(id: :desc)
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render "homes/sns"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインできませんでした"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録完了"
      redirect_to root_url
    else
      flash.now[:danger] = "登録失敗"
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/homes/biography.html.erb
<%= render "layouts/localnav" %>

app/views/homes/discography.html.erb
  <%= render "layouts/localnav" %>
  
  <main class="asunan-main">
    <article class="asunan-wrap">
      <section class="asunan-disco-wrap">
        <div class="asunan-disco-item">
          <div class="asunan-disco-inner">
            <h3 class="asunan-disco-ttl">Daylight</h3>
            <div class="asunan-disco-img">
              <img id="daylight-img" src="/assets/Daylight.jpg" alt>
            </div>
            <div id="asunan-daylight">
              <div>
                <p class="asunan-music-list">
                  <strong>Playlist</strong>
                  <br>
                  <span>01. Daylight</span>
                  <br>
                  <span>02. PROGRESS 0!</span>
                  <br>
                  <span>03. Thermit</span>
                  <br>
                  <span>04.	48 reasons to poison*you*.</span>
                  <br>
                  <span>05. 無題 -unphase-</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="asunan-disco-item">
          <div class="asunan-disco-inner">
              <h3>Twilight</h3>
              <div class="asunan-disco-img">
              <img id="twilight-img" src="/assets/Twilight.png">
              </div>
              <div id="asunan-twilight">
                <div>
                  <p class="asunan-music-list">
                    <strong>Playlist</strong>
                    <br>
                    <span>01. twilight</span>
                    <br>
                    <span>02. 時雨日和 (Vo. IA, 初音ミク)</span>
                    <br>
                    <span>03. なんでもいいよ♡たび</span>
                    <br>
                    <span>04.	怪奇！<ruby>狂詩曲人間<rt>《ラプソディ・マン》</rt></ruby></span>
                    <br>
                    <span>05. when the moon *sets*.</span>
                  </p>
                </div>
              </div>
            </div>
        </div>
      </section>
    </article>
  </main>

app/views/homes/index.html.erb
<div id="loading">
  <div class="spinner">
  </div>
</div>

<div id="wrapper">
  
  <%= render 'layouts/navbar' %>
  
  <div>
    <img id="asunan-sano" src="/assets/illust_compiration.jpg" alt>
  </div>
  <h2 class="bunner1">NEWS</h2>
    
  <div id="news">
      <ul>
        <li>
          <span>
          <a href=""></a>
          </span>
        </li>
        <li>
          <span>
          <a href=""></a>
          </span>
        </li>
        <li>
          <span>
          <a href=""></a>
          </span>
        </li>
      </ul>
    </div>
    <div>
      <video src="/DaylightTwilightM3.mp4" controls playsinline type="video/mp4" preload="auto"></video>
    </div>
  <footer>
      
  </footer>
</div>

<p id="top-btn-text">TOP</p>

app/views/homes/members.html.erb
<%= render "layouts/localnav" %>

app/views/homes/sns.html.erb
<%= render "layouts/navbar" %>

<div class="container sns-wrap">
  <div class="row">
    
    <div class="col-sm-8">

      <%= render 'microposts/microposts', microposts: @microposts %>

    </div>
      
    <aside class="col-sm-4">
      <%= form_with(model: @micropost) do |f| %>
        <div class="mb-3">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit '投稿', class: 'btn btn-primary w-100' %>
      <% end %>
    </aside>
    
  </div>
</div>

app/views/homes/special.html.erb
<%= render "layouts/localnav" %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_localnav.html.erb
<header>
  <div id="ashitamochi">
    <a href="/"><img class="ashitamochi" src="/assets/ashitamochi.png" alt="あしたもち"></a>
  </div>
  <h2 id="asunan">あしたまでになんとかしておきます</h2>
</header>

<nav class="global_nav">
  <ul>
    <li class="js_nav">
      <%= link_to "Home", root_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Discography", discography_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Members", members_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Biography", biography_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "SNS", sns_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Store", products_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Special", special_path =%>
    </li>
  </ul>
</nav>

app/views/layouts/_navbar.html.erb
<div class="nav-btn">
    <div></div>
    <div></div>
    <div></div>
  </div>

<header>
  <div id="ashitamochi">
    <a href="/"><img class="ashitamochi" src="/assets/ashitamochi.png" alt="あしたもち"></a>
  </div>
  <h2 id="asunan">あしたまでになんとかしておきます</h2>
</header>

<nav class="global_nav">
  <ul>
    <li class="js_nav">
      <%= link_to "Home", root_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Discography", discography_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Members", members_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Biography", biography_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "SNS", sns_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Store", products_path =%>
    </li>
    <li class="js_nav">
      <%= link_to "Special", special_path =%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Asunan Official</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false" oncontextmenu="return false;">
      <%#= render 'layouts/navbar' %>

      <%= render 'layouts/flash_messages' %>

      <%= yield %>

      <img id="top-btn" src="/assets/ashitamochi.png" alt="あしたもち">

  </body>
</html>

app/views/microposts/_microposts.html.erb
<% if @microposts.any? %>
  <ul class="list-unstyled mt-2">
    <% @microposts.each do |micropost| %>
      <li class="d-flex">
        <div>
          <div>
            <%= link_to micropost.user.name, root_url, class: "text-decoration-none user-name--" %> <span class="text-muted txt-muted">posted at <%= micropost.created_at %></span>
          </div>
          <div>
            <p><%= micropost.content %></p>
          </div>
          <div class="delete-btn">
            <% if current_user == micropost.user %>
              <%= button_to "Delete", micropost, method: :delete, data: { confirm: "削除する？" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/products/index.html.erb
<div>
  
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div>
  <h2>あすなんPREMIUM</h2>
</div>

<div>
  <%= form_with(model: @user) do |f| %>
  
    <div class="input--">
      <%= f.label :name, "ペンネーム" %>
      <%= f.text_field :name %>
    </div>
  
    <div class="input--">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
    </div>
    
    <div class="input--">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>
    </div>
    
    <div class="input--">
      <%= f.label :password_confirmation, 'パスワード確認用' %>
      <%= f.password_field :password_confirmation %>
    </div>
    
    <%= check_box_tag :check %>
    <%= label_tag :check, "アカウント情報を記憶する" %>
    
    <%= f.submit '登録', class: 'login-btn' %>
  <% end %>
  
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>